version: "3"
services:
    whatsapp-chatgpt:
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "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"
            PREFIX_ENABLED: "true"
